export const MSG = {
  ORDERS_CANDIDATES: 'ORDERS_CANDIDATES',
  NETWORK_PAYLOAD: 'NETWORK_PAYLOAD',
  LOGIN_DETECTED: 'LOGIN_DETECTED',
  RESUME_PLATFORM: 'RESUME_PLATFORM',
  GET_STATE: 'GET_STATE',
  SAVE_SETTINGS: 'SAVE_SETTINGS',
  UPSERT_PLATFORM: 'UPSERT_PLATFORM',
  REMOVE_PLATFORM: 'REMOVE_PLATFORM',
  TEST_EMAIL: 'TEST_EMAIL',
  RETRY_PENDING: 'RETRY_PENDING',
}
